### ISSUE TITLE
Modules not found

### ISSUE THREAD

**Issue by ozej8y** [NeuroDesk/vnm#101]
After following the instructions to run the Neurodesk docker container on my Mac, when I try to start an application, errors are returned about the module being unknown.

When I run 'module avail' nothing is returned. 
Modules are not correctly setup.

I tried running "./fetch_and_run.sh fsl 6.0.3 20200905", it has the same moduel unknown error.

I am using the Docker container: vnmd/neurodesk:20201120

Please assist.

Thanks,
              Jay.

**Comment by stebo85** [comment]
Dear Jay,

Thank you so much for trying neurodesk, finding this bug and opening an issue :) This bug only occurs for an empty environment where the module folder has not been created yet - so it slipped through my testing ... 

Bug is now fixed: Can you try the latest container version 20201127 and let me know if it is working for you?

Also, super happy to hear what you think about the project and I am sure there are more bugs just waiting to be found and covered by a unit test :p

**Comment by ozej8y** [comment]
Hi Steffan,

Thanks for the quick response. I'm investigating how your containers run, as we are looking at how to incorporate them into the CVL container repo: https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software 

It's working now.

Thanks, 
               Jay.

**Comment by stebo85** [comment]
Dear @ozej8y ,

Great to hear it's working now 👍 

We integrated neurodesk with CVL at UQ by installing it in the CLI mode - would that work for you?
https://github.com/NeuroDesk/neurodesk/

Cheers
Steffen

**Comment by stebo85** [comment]
@ozej8y, are there any updates from your side? Can I close this issues :?

Cheers
Steffen

**Comment by ozej8y** [comment]
Hi Steffen,

Yes issue fixed. Please close.

Thanks,
             Jay.
