### ISSUE TITLE
Add some basic utilities to base image

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#102]
Add these:
- sshfs
- ping

**Comment by stebo85** [comment]
yes, good idea. You can do this in the dockerfile in this repo (https://github.com/NeuroDesk/vnm/blob/master/vnm_base/Dockerfile) and then build a new base image that you use in the neurodesk repo as a base for vnm (https://github.com/NeuroDesk/neurodesk/blob/master/vnm/Dockerfile)

**Comment by stebo85** [comment]
Dear @civier ,

I added sshfs and ping. It's in the latest version:

sudo docker run --privileged --name vnm -e RESOLUTION=1620x960 -e USER=neuro -v ~/vnm:/vnm -v /dev/shm:/dev/shm -p 6080:80 -p 5900:5900 vnmd/vnm:20210130
