### ISSUE TITLE
Adding basic software to VNM base image? E.g. simple text editor

### ISSUE THREAD

**Issue by TomEmotion** [NeuroDesk/vnm#104]
Wondering what the procedure should be for suggestions for basic software additions to the VNM base image? Can we start a list somewhere?

First suggestion from me: basic text editor that looks/feels like a Windows/Mac/Linux GUI text editor. Something that also uses keyboard shortcuts for copy/paste etc that are consistent with VNM desktop. Emacs is too geeky & idiosyncratic for many users. GEdit is fine, but perhaps there is something similar but better.

**Comment by stebo85** [comment]
Dear @TomEmotion,

the easiest is to open an issue as you did, then we can reference it in the pull request adding the requested tool. Gedit is a great idea to add. The easiest point to add would be here: https://github.com/NeuroDesk/vnm/blob/master/vnm_base/Dockerfile

If you don't have time to add it I can look at this once the CVMFS refactoring is done :)

Cheers
Steffen

**Comment by aswinnarayanan** [comment]
@TomEmotion Would Visual Studio Code be a suitable option? (https://code.visualstudio.com/)

**Comment by TomEmotion** [comment]
> @TomEmotion Would Visual Studio Code be a suitable option? (https://code.visualstudio.com/)

I have also installed Spyder as an IDE with text editor using Conda in an experimental version of VNM that I'm trying out. Visualstudio looks like a nice editor for coders, with a nice feature set.

But I think a really simple, basic text editor is needed. One that non-technical users can use to view Readme files, open cvs/tsv files, and do simple editing of shell scripts/batch scripts. And one that doesn't confuse or intimidate them with lots of features and menus centred around coding.

**Comment by stebo85** [comment]
@TomEmotion,

I added gedit to the latest version of the image :)

Can you test? New image version is 20210512

**Comment by TomEmotion** [comment]
> @TomEmotion,
> 
> I added gedit to the latest version of the image :)
> 
> Can you test? New image version is 20210512

Will do - thanks!
