### ISSUE TITLE
High storage comsumption on windows.

### ISSUE THREAD

**Issue by yjmantilla** [NeuroDesk/vnm#105]
So the problem I had is that docker by default installs everything (including containers) on the c:drive , which for many people is size limited.

As you use the VNM, the space of the virtual hard disk for the vnm never shrinkes, so you will see your space quickly being depleted. This happens at least with the WSL2 backend, which is the most recommended (if I remember correctly).

I managed to fix it being looking around on the web, the best approach i found is here:

https://yjmantilla.github.io/tutorials/wsl2-move-vhdx.html

Let me know if i shall push this into the wiki or something (with more explanation if needed).

**Comment by stebo85** [comment]
Dear @yjmantilla - it would be interesting to understand why your VNM install requires so much space. There are two components and we tried to reduce the local space consumption as much as possible:
1) There is the docker container running VNM: This is stored in the VHDX file you are describing and your solution should work to reduce the space. I can add this to the README. HOWEVER: the VNM container shouldn't consume much space unless you are manually adding packages, which is not recommended. Can you check how much space your VNM consumes?

2) There is the mounted directory where we store the sub-containers in (by default C:/vnm) - this location you can change via the docker starting command. However, also here in the latest version we are not downloading the containers but rather try to use them on demand from our CVMFS storage, so this directory shouldn't contain much data either.

It would be great to understand what consumes how much in your case and identify what when wrong :)

Cheers
Steffen

**Comment by aswinnarayanan** [comment]
Thanks @yjmantilla 
Minimum space requirements is now in the readme
And your instructions is now in the wiki and advanced instructions
