### ISSUE TITLE
Using VNM as a root user through Azure

### ISSUE THREAD

**Issue by lukevano** [NeuroDesk/vnm#106]
Thank you for this fantastic package! I've been able to run it locally on my laptop but it's a bit too slow so have been getting up the docker on Azure. I can bring up the virtual machine using the following code but can't download my data as I'm not a root user:

sudo docker run --privileged --name vnm -v ~/vnm:/vnm -v /dev/shm:/dev/shm -e USER=neuro -p 6080:80 -p 5900:5900 vnmd/neurodesk:20201127

I get this comment when the code runs:
cp: cannot stat '/root/.config': No such file or directory
2021-09-05 15:17:55,089 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
I'm able to get the VNM working but can't load my own data ask I'm not the root user. Do you know if there is a way around this?

Is there a way to get this working?

**Comment by stebo85** [comment]
Dear @lukevano,

Cool - thank you for trying out our project :)

The error you see is not a problem - you can ignore it and the desktop should run without any problems.

Let me know if this is the case or if anything else is not working as expected :)

Kind regards
Steffen

**Comment by lukevano** [comment]
Many thanks! I was making an error with the docker code. All fixed now and enjoying it.

Best wishes,
Luke

**Comment by stebo85** [comment]
Dear @lukevano 

That's great to hear :) We are also currently working on the next version of the NeuroDesk interface that we will release on the 20th of September with lots
