### ISSUE TITLE
write script to pull containers via transparent-singularity and install them in a persistent space

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#13]
https://github.com/NeuroDesk/transparent-singularity

**Comment by MartinGrignard** [comment]
Once `lmod` will work, it should be really straightforward given the `transparent-singularity` script. I tried it with itksnap and it's very easy.
Basically, what we should do is just a little script that checks if the desired module is in the list, if not, check if it is available in any repositoy we will list, pull it and install it if needed, load the resulting module and run it. As transparent-singularity is currently dedicated to CAI, should we fork it to make a script which could check multiple mirrors/remotes?

**Comment by stebo85** [comment]
transparent-singularity is not dedicated to CAI :) We are using it now in 3 different projects. I forked the repo in this organization so we can make quick changes, but ideally I like to see all these improvements can be migrated to the main project and make it work for everyone who wants to use it :)

**Comment by MartinGrignard** [comment]
Ok, I thought it was a tool for your lab but it's nice seeing you want to make it as flexible as possible! :)
