### ISSUE TITLE
test master container in singularity and on HPC

### ISSUE THREAD

**Issue by crnolan** [NeuroDesk/vnm#16]
Idea is to allow the entire container structure to be identical between HPCs and desktops.

**Comment by kaczmarj** [comment]
what about building a docker image (which is the most portable) and then converting that to singularity? that seems like the least work to maintain

**Comment by stebo85** [comment]
yes, correct :) Converting the docker image to singularity on the HPC is what I have in mind (and keep developing in a docker container and for windows). This issue is about looking into nesting singularity containers, so that the rest we are doing still works on an HPC.

**Comment by crnolan** [comment]
Yep, sorry that could have been a clearer description :)

**Comment by stebo85** [comment]
I looked into running VNM on our HPC and I made some progress :)
the container converts and runs:
singularity shell -e -B /gpfs1/scratch/30days/uqsbollm/test:/vnm vnm.sif

however, I haven't found out how to run a singularity container inside a singularity container:
/usr/share/fetch_and_run.sh convert3d 1.0.0 20200420
convert3d/1.0.0
Module 'convert3d/1.0.0' is installed. Use the command 'module load convert3d/1.0.0' outside of this shell to use it.
ERROR  : Failed to set effective UID to 0

Trying to run the vnm container with fakeroot option gave me:
singularity shell -f -e -B /gpfs1/scratch/30days/uqsbollm/test:/vnm vnm.sif
INFO:    Convert SIF file to sandbox...
FATAL:   could not use fakeroot: no mapping entry found in /etc/subuid for uqsbollm

The singularity mailinglist suggests, that it is possible what we are trying:
"Singularity does not allow setuid executables inside of containers.
Depending on the host operating system (that is, if it is fairly modern)
and what you're trying to do you may be able to run singularity
unprivileged inside of another singularity container."

Maybe we are better off, simplying the fetch_and_pull script to setup a similiar experience to VNM inside an HPC environemnt without running inside a container?

**Comment by stebo85** [comment]
closing that for now, because I could not find a way of running nested singularity containers on HPCs -> alternative solution could be to create a nice bash script in the repo "neurodesk" that handles multiple containers on HPCs in a nice and user-friendly way (including "importing" the exact software state that one was using in the VNM container on a different computer)

**Comment by crnolan** [comment]
Interesting, I was testing this out last week but didn't finish. I'll reopen if I get anywhere.

**Comment by stebo85** [comment]
Cool :) would be interesting to hear what you find out

**Comment by civier** [comment]
Hello Steffen,
As I mentioned before, I already looked at it, and it should be possible with certain settings on HPC and sandbox Singularity image. I re-post what I posted on Mattermost:

> "I only looked into this issue briefly and read about a possible solution, which is discussed here:
> https://github.com/sylabs/singularity/issues/4037
> (see last comment in the thread from DrDaveD, Aug 2nd 2019)
> 
> From my understanding, Singularity disallows running SUID programs within a container due to security concerns. Therefore, standard singularity containers cannot be run from within other containers.
> However, from October 2016, Singularity supports User Namespace (https://singularity.lbl.gov/docs-security#how-does-singularity-do-it), and then if the outer container is being executed unprivileged, so running another container within should be possible. I'm not sure though if the inner container can be a standard one, or whether it must be executed unprivileged as well? (do you know? did you try unprivileged containers?)
> 
> One caveat is the RHEL version required, but according to the version mentioned in the last comment in the thread above (Kernel version 3.10.0-957 or later), both MASSIVE and OzStar have an adequate version. Also, I checked, and the CONFIG_USER_NS option is enabled in both HPCs.
> 
> Running unprivileged containers entails of course several limitations such as that the "sandbox" image must be used, but if it is only the outer container that needs to be executed this way, maybe it can work for us. The following page discusses the limitation of running containers unprivileged:
> https://opensciencegrid.org/docs/worker-node/install-singularity/#choosing-unprivileged-vs-privileged-singularity"

**Comment by stebo85** [comment]
yes, this is what I thought I tried.

**Comment by stebo85** [comment]
Closing this for now. I updated transparent singularity https://github.com/NeuroDesk/transparent-singularity to pull all our VNM containers directly onto HPCs and I personally think that this is the best solution, because it nicely integrates into job-submission systems like Slurm and PBS. Running containers nested on an HPC seems appealing, but I can't get it to work. Please feel free to re-open if anyone makes progress on this idea. For my own workflows on ouf HPCs I found transparent-singularity to be a very nice solution and I don't have any problems with this - maybe we could add more documentation to make the HPC side easier for users?

**Comment by crnolan** [comment]
The only downside this way I guess is that one can't necessarily fully mirror the desktop and HPC environment (i.e. use the same master image for both). So I guess the way to look at it instead is the docker image is attempting to mirror the eventual HPC environment.
