### ISSUE TITLE
CI+CD: Automatically build the master image and push to docker hub and test if working

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#22]

**Comment by kaczmarj** [comment]
DockerHub has an automated builder. You can link the DockerHub repository to here and tell it to build the latest image on an any push to master.

**Comment by stebo85** [comment]
yes, DockerHub would be perfect for this. I was thinking to also host all images we need in this project in an organization account on docker hub. I just created an org there "https://hub.docker.com/orgs/vnmd" - can please everyone send me their docker hub account ids (I think we can have 3 accounts linked to a free organization)

**Comment by stebo85** [comment]
I setup the automatic builds, but there is no testing yet. What would be a good automatic test if the container "runs"?
