### ISSUE TITLE
simplify adding containers to the menu

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#35]
Currently one needs to copy multiple files and manually change them to create a new software entry in the main menu. Would it be cool to have a simple textfile where we enter which images are ready and tested and based on this we generate all menu entries automagically?

**Comment by MartinGrignard** [comment]
This would also clean the repository as we could actually run the script during the build of the container thus removing all the menu files from the directory and even reducing the amount of layers required to generate the menu items.

**Comment by MartinGrignard** [comment]
I'm working on a solution based on a `.json` config file where we would have to specify the information. This file would look like:
```json
{
    "Some tool": {
        "icon": "/home/neuro/.config/lxpanel/LXDE/icons/vnm.png",
        "apps": {
            "Some tool X.X.X": {
                "version": "X.X.X",
                "icon": "/home/neuro/.config/lxpanel/LXDE/icons/vnm.png",
                "exec": "bash /usr/share/fetch_and_run.sh sometool X.X.X YYYYMMDD",
                "comment": "A comment",
                "terminal": true
            }
        }
    }
}
```

**Comment by stebo85** [comment]
Dear @MartinGrignard - this is great! I love the idea and what you have in the issue branch looks perfect to me.

In order to separate things out in different repos and make the different components reusable in other projects: 
* would it be ok, to store all menu related things in our permanent storage /vnm? and softlink them to the correct locations (dependent on the distribution and desktop flavor running?) 
* have the code to do all of that in the https://github.com/NeuroDesk/neurodesk repo

**Comment by MartinGrignard** [comment]
Hi 😁 I still have somme tweeks to do before the script is ready but it is alpost donne.
I think it would be possible but then the script could not be ran during the build, would it be ok to run a setup script at start?

**Comment by stebo85** [comment]
True @MartinGrignard - I did not consider this problem :) 

Then I think it's better to put the menu entries at the right spot in VNM and we build in a paramter that saves the menu files in /vnm for the other projects using the menu system in the neurodesk repo.

Yes, downloading and adding the latest config file during build is good. This makes it easy for users and we can control what software is available in VNM via changing the config file and triggering a rebuild.

**Comment by stebo85** [comment]
Hi @MartinGrignard - I was wondering if there is anything I can help with at the moment with respect to getting the menus working? There is a container roundtable on Thursday and I was wondering if we could have a new release by then with a lot more software :?

**Comment by MartinGrignard** [comment]
Hi @stebo85! I'm sorry it took so long, I've had issues with other projects lately... I'll work on it today and ship it. Is neurodesk added as a subproject in the repo of vnm? It would make things easy to integrate in the docker image.

**Comment by stebo85** [comment]
Hi @MartinGrignard - no worries :) I was just wondering if I can help :) The neurodesk repo is not added as a subproject - I was just thinking of cloning it to vnm (instead of copying files :?) i haven't worked much with subprojects yet, so happy to see what one can do with these

**Comment by MartinGrignard** [comment]
For the help, I'm currently testing if everything's okay with the `build_meny.py` script, if it works with two test apps, it should work with more.

For the subproject, as VNM should actually include neurodesk to work, it would be a great solution to add it as a subproject as it would involve working with the latest version at anytime. I've only used this in some simple cases like here where there is a one-way dependency and it works quiet well. The only issue is that it means that the rebuild of the image would not be triggered by a push to neurodesk...

**Comment by MartinGrignard** [comment]
@stebo85 I've built the image and I come across a strange issue:
All the files are written in the right place and seem to contain what they should but the menu does not appear.
The only problem I can seem to find is that the formatting of the added entries to `vnm-applications.menu` does not include indentation. Do you think it might be the problem?

**Comment by MartinGrignard** [comment]
The branch [35-simplify-adding-containers](https://github.com/NeuroDesk/vnm/tree/feature/35-simplify-adding-containers) now creates a prettified xml file so it seems that the issue does not come from the file format...

If you have any idea why the menu does not appear with all the files being in the right place and having the right permission, it would help a lot :stuck_out_tongue: I continue my investigation.

**Comment by MartinGrignard** [comment]
Commit NeuroDesk/vnm@80b9a72bf3d62efdb0a8dffc3e129a5808722cb4 fixed the case issue. The only remaining problem is that the main VNM menu does not show up as we want it to:
![image](https://user-images.githubusercontent.com/14327643/86003871-be1d7280-ba12-11ea-9f0e-c3dd100fa65e.png)

**Comment by aswinnarayanan** [comment]
Hi @MartinGrignard, vnm-neuroimaging.directory isn't being added to the container because its not on the application list. Adding it in fixes the main menu
