### ISSUE TITLE
seperate handling of software containers into its own repo (neurodesk) 

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#36]
-> this then will be the HPC version of VNM because I am quite certain now that nesting singularity containers does not work on HPCs, because singularity needs higher privileges than we can ever obtain on an HPC safely.

**Comment by civier** [comment]
Hello Steffen. Where did you find this information about privileges required for the singularity? Can you send me the info/links?

**Comment by stebo85** [comment]
yes, all info about this is here: https://github.com/NeuroDesk/vnm/issues/16

**Comment by stebo85** [comment]
closing since discussion is happening in #40
