### ISSUE TITLE
modularization of our code in different Repos

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#40]
Hi all :)

I would love to have everyone's opinion on our current architecture and possible changes: https://github.com/NeuroDesk/vnm/wiki/Architecture

Goal: I would like to have different parts of the project in separate repos that allow easy testing, issue handling and easier collaboration.

**Comment by stebo85** [comment]
@MartinGrignard, I am hoping that we can make the menus general enough so they would work in different Linux desktops and not just lxde - I therefore thought it's a good idea to have the menus in the neurodesk repo and with this separated from VNM. This would then allow to install neurodesk on VNM, a "normal" bare-metal Linux desktop and we can use neurodesk in the CVL project as well. The top layer would only make minimal adjustments to the menu, e.g. linking the files to the right spots in mate, lxde, xfce.

I see VNM as the top layer that provides a simple desktop to users on mac and windows - it should all be super userfriendly and all complexity should be abstracted away. Everything handling menus and containers should happen in neurodesk. Everything that needs containers and the module system should happen below that in transparent-singularity (we could then re-use this on the HPCs, because there we don't need to handle menus)

Does this make sense?

**Comment by MartinGrignard** [comment]
It does make sense! Now I understand 😊 so once my work on making adding apps easier will work properly I'll move it to neurodesk.

**Comment by stebo85** [comment]
Cool :) Yes, when it works and you are keen you can move the menu code over to the neurodesk repo. I am also happy to help :) Let me know! I made some improvements today on vnm that hopefully shouldn't interfere with your work, so a rebase of your branch onto master should be easy before merging.

**Comment by stebo85** [comment]
refactoring finished and menu system generation is now in neurodesk repo https://github.com/NeuroDesk/neurodesk enabling a deployment on any linux system with lxde desktop and extendable to other desktop systems
