### ISSUE TITLE
switch automatic build of VNM to github actions

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#57]

**Comment by stebo85** [comment]
in the github actions I would also like to build in tests if the image builds correctly and the basic functionality works. Would it be ok for everyone if we then also start protecting the master branch, so that only commits that create a working container can be merged?

@aswinnarayanan @MartinGrignard @civier

**Comment by MartinGrignard** [comment]
@stebo85 sure!

**Comment by aswinnarayanan** [comment]
Sounds good 👍

**Comment by aswinnarayanan** [comment]
Initial commit ed3fac5b331364ada9fa71847484bc9aab9cb181 keeps rebuilding the image from scratch, there's some issue with the caching

**Comment by stebo85** [comment]
This is awesome! Thank you. No idea why the caching is not yet working, but I am happy with this as is! Thank you so much @aswinnarayanan :)
