### ISSUE TITLE
creating a light and a full version of VNM

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#71]
What do people think about creating a lightwight VNM container version that only includes the absolutely necessary tools to run the external software packages (i.e. singularity and menu system) and then use this a basis image for a version with more features (i.e. python, julia, vs code, rclone, ....) - is that useful :?

**Comment by aswinnarayanan** [comment]
Related to #40 #58
Is this not the original model that was proposed? I.e. very lightweight minimal container, that add optional software containers from caid or elsewhere

**Comment by stebo85** [comment]
yes, correct - but we are limited in what we can do in separate containers: e.g. everything that is on the pipeline side and managing data is better in the main container - the problem is that the main container grows quite a bit because of this - we are currently at 2.6GB for VNM. 

I was thinking that we could now easily build multiple flavours since the github actions allow that nicecly :)

**Comment by stebo85** [comment]
closed for now.
