### ISSUE TITLE
modify Application menu

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#8]
@aswinnarayanan, could you let us know how you modified the menu on the cai-workstatations :? We are using the same desktop environment in this project :)

**Comment by aswinnarayanan** [comment]
@stebo85, Ive noted it down on this gist, will update. I'll add some notes on nesting sub-menus and using mergediles for sub-menus shortly
https://gist.github.com/aswinnarayanan/5926e21794949c86b25ffbda34d8f2cd

**Comment by stebo85** [comment]
Awesome :) Thank you much @aswinnarayanan !!!!

**Comment by aswinnarayanan** [comment]
@stebo85 https://github.com/NeuroDesk/vnm/tree/feature/appmenus
This has menu, nested sub-menus and application for lxde configured
I've used lxterminal as an example application.

It should integrate easily with transparent singularity, might need to rename some folder here though

**Comment by MartinGrignard** [comment]
If it's already usable as is, I can merge it and use it to add the first tools :) is it ok for you @aswinnarayanan?

**Comment by aswinnarayanan** [comment]
Its already usable, happy to have it merged, 
Feel free to rename any of the menus & categories :)

**Comment by MartinGrignard** [comment]
Fine, I just had to add the icon so that we could build but great thanks for your help on this, I had never configured Xfce :D
