### ISSUE TITLE
Install basic popoular linux utilities in main image

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#81]
I found out that these very basic Linux utils are missing:
- less
- ImageMagick (aka "display")
- tree
- nano
- vim
- emacs

I believe these shouldn't take much space at all, so why not adding them?

**Comment by stebo85** [comment]
yes, possible :)

**Comment by civier** [comment]
also:
- gimp

Not sure how big it is, though?
Also, any recommendation on Window's Paint-compatible bitmap editor? (for those not comfortable with gimp) I'm looking for one for years already.

**Comment by stebo85** [comment]
gimp is big - but we can try

**Comment by stebo85** [comment]
ok, all working :)
