### ISSUE TITLE
Choosing an application from the menu should run the GUI

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#86]
I envision the menu to not only download the packages, but also run the GUI of each package (fsl, mrview, freeview, afni, spm, etc.)
Do you agree? If yes, can you implement it?
Also, if the package is already downloaded, pressing the menu should only run the GUI.

**Comment by stebo85** [comment]
Running the GUI by default is not a good idea, because then you force every user to use the module system when they want to run a non gui tool from the package. What we could do is to add another menu item that runs the GUI tool?

**Comment by civier** [comment]
Sure. For every tool, we can have one option to open a terminal and load
the module, and another option to run the GUI.

To be honest, though, I wonder how much people would actually use the first
option (terminal). The reason is that if you load the module through the
menu and then want to run commands through the terminal, so:
1) you need to navigate to where your files are
2) you lose your command history
3) if you use multiple packages, you need to load the rest of them with the
module command anyway
So it is very possible that for command-line work, users would prefer to
stick to a single terminal and use the module command to load packages.

**Comment by stebo85** [comment]
yes, that's correct - we want to give users every possible way of working and not restrict anything.

**Comment by stebo85** [comment]
done
