### ISSUE TITLE
Information on progress and termination of package downloads

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#87]
Right now, one knows that the download terminated when the "singularity>" prompt is presented in the terminal window. Instead, I think we should present a big message saying "Download completed" and also print to the terminal the module name that should be used. When the user presses ENTER, the terminal window can then be closed.
Any thoughts? I guess it is trivial to implement if you agree.

**Comment by stebo85** [comment]
yes, this can be done :)

**Comment by stebo85** [comment]
done
