### ISSUE TITLE
Update to FreeSurfer 7.1.1

### ISSUE THREAD

**Issue by pwighton** [NeuroDesk/vnm#98]
Is it possible to update FreeSurfer to 7.1.1?

Neurodocker has been [updated](https://github.com/ReproNim/neurodocker/pull/363).

Is it as simple as a changing [this line](https://github.com/NeuroDesk/caid/blob/b169d5d818e280ab401b650b0c30d417211e578a/recipes/freesurfer/build.sh#L10)?

I'm happy to submit a PR if pointed in the right direction.

**Comment by stebo85** [comment]
Dear @pwighton,

I merged the latest changes from neurodocker into our fork (because we added more packages to neurodocker that are still not merged) and triggered a build of the freesurfer 7.1.1 container - it should be ready to test in an hour.

Cheers
Steffen

**Comment by stebo85** [comment]
Dear @pwighton ,

Freesurfer 7.1.1 is now in the latest version of VNM. Pull the container version 20200924 and let me know if something isn't working for you :) 

closing for now, but please feel free to reopen.

Cheers
Steffen

**Comment by pwighton** [comment]
Thanks so much for the quick reply, @stebo85 !

I can confirm FreeSurfer 7.1.1 is in `20200924`.  And there's even an icon now for FreeView in the launch menu.  Very cool! :)

**Comment by stebo85** [comment]
@pwighton - I am glad it's working and you like the Freeview icon. Any other ideas or suggestions to improve feel free to open an issue :)
